substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _WEP_APP_IMAGE: ${WEP_APP_IMAGE}
  _REPO_WEB_APP: ${REPO_WEB_APP}
  _LOCATION: ${LOCATION}

options:
    volumes:
    - name: 'ssh'
      path: '/root/.ssh'

steps:
# SSHキーとknown_hostsファイルをセットアップ
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=secret-name > /root/.ssh/id_github
    chmod 600 /root/.ssh/id_github
    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

# GitHubからclone
- name: 'gcr.io/cloud-builders/git'
  args:
  - '-c'
  - 'core.sshCommand=ssh -i /root/.ssh/id_github -o UserKnownHostsFile=/root/.ssh/known_hosts'
  - 'clone'
  - 'git@github.com:kojikawazu/next-ts-intro-web-app.git'

# Docker を設定
- name: 'gcr.io/cloud-builders/docker'
  args: ['login', 'asia-northeast1-docker.pkg.dev']

# 環境変数の設定
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e

    # Get secrets from Secret Manager and export them as environment variables
    export PROJECT_ID=$(gcloud secrets versions access latest --secret=project-id --format='get(payload.data)' | base64 --decode)
    export WEP_APP_IMAGE=$(gcloud secrets versions access latest --secret=web-app-image --format='get(payload.data)' | base64 --decode)
    export REPO_WEB_APP=$(gcloud secrets versions access latest --secret=repo-web-app --format='get(payload.data)' | base64 --decode)
    export LOCATION=$(gcloud secrets versions access latest --secret=location --format='get(payload.data)' | base64 --decode)

    # Print the variables to the log (optional, for debugging purposes)
    echo "PROJECT_ID: $PROJECT_ID"
    echo "WEP_APP_IMAGE: $WEP_APP_IMAGE"
    echo "REPO_WEB_APP: $REPO_WEB_APP"
    echo "LOCATION: $LOCATION"

    cd next-ts-intro-web-app
    gcloud secrets versions access latest --secret=node-env > temp.txt
    echo "NODE_ENV=$(cat temp.txt)" > .env
    gcloud secrets versions access latest --secret=app-env > temp.txt
    echo "APP_ENV=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-get-intro-json-prod > temp.txt
    echo "NEXT_PUBLIC_GET_INTRO_JSON_PROD=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-get-intro-json > temp.txt
    echo "NEXT_PUBLIC_GET_INTRO_JSON=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-send-mail-url-prod > temp.txt
    echo "NEXT_PUBLIC_SEND_MAIL_URL_PROD=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-send-mail-url > temp.txt
    echo "NEXT_PUBLIC_SEND_MAIL_URL=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-send-error-log-prod > temp.txt
    echo "NEXT_PUBLIC_SEND_ERROR_LOG_PROD=$(cat temp.txt)" >> .env
    gcloud secrets versions access latest --secret=next-public-send-error-log > temp.txt
    echo "NEXT_PUBLIC_SEND_ERROR_LOG=$(cat temp.txt)" >> .env
    rm temp.txt

# ステップ 5: 最新のイメージをバックアップ
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE}:latest || true
    if [ $? -eq 0 ]; then
      docker tag ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE}:latest ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE}:backup
      docker push ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE}:backup
    fi

# ステップ 6: Docker イメージをビルドしてプッシュ
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE} ./next-ts-intro-web-app,
    docker push ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_WEB_APP}/${_WEP_APP_IMAGE}
