name: Build and Deploy to GCR

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_PRI_NAME }}
  # Web App Image
  IMAGE_NAME: next-ts-intro-web-app-image
  # Artifact Registry
  REPO_NAME: registory-intro-web-app
  LOCATION: asia-northeast1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup .env file
      run: |
        echo "NEXT_PUBLIC_GET_INTRO_JSON_PROD=${{ secrets.NEXT_PUBLIC_GET_INTRO_JSON_PROD }}" >> .env
        echo "NEXT_PUBLIC_GET_INTRO_JSON=${{ secrets.NEXT_PUBLIC_GET_INTRO_JSON }}" >> .env
        echo "NEXT_PUBLIC_SEND_MAIL_URL_PROD=${{ secrets.NEXT_PUBLIC_SEND_MAIL_URL_PROD }}" >> .env
        echo "NEXT_PUBLIC_SEND_MAIL_URL=${{ secrets.NEXT_PUBLIC_SEND_MAIL_URL }}" >> .env
        echo "NEXT_PUBLIC_SEND_ERROR_LOG_PROD=${{ secrets.NEXT_PUBLIC_SEND_ERROR_LOG_PROD }}" >> .env
        echo "NEXT_PUBLIC_SEND_ERROR_LOG=${{ secrets.NEXT_PUBLIC_SEND_ERROR_LOG }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_NAME=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_NAME }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_EMAIL=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_EMAIL }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_MESSAGE=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_MESSAGE }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_CONFIRM=${{ secrets.NEXT_PUBLIC_CONTACT_CONFIRM }}" >> .env
        echo "NEXT_PUBLIC_MAIN_TITLE_PREFIX=${{ secrets.NEXT_PUBLIC_MAIN_TITLE_PREFIX }}" >> .env
        echo "NEXT_PUBLIC_NOTICE_SUCCESSED=${{ secrets.NEXT_PUBLIC_NOTICE_SUCCESSED }}" >> .env
        echo "NEXT_PUBLIC_NOTICE_FAILED=${{ secrets.NEXT_PUBLIC_NOTICE_FAILED }}" >> .env
        echo "NEXT_PUBLIC_SKILLS_CARD_FIRST_SHOW_SUM=${{ secrets.NEXT_PUBLIC_SKILLS_CARD_FIRST_SHOW_SUM }}" >> .env
        echo "NEXT_PUBLIC_SKILLS_CARD_LOAD_COUNT=${{ secrets.NEXT_PUBLIC_SKILLS_CARD_LOAD_COUNT }}" >> .env

    - name: Configure Docker
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
