name: Build and Deploy to GCR

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_PRI_NAME }}
  IMAGE_NAME: next-ts-intro-web-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Google Cloud Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup .env file
      run: |
        echo "NEXT_PUBLIC_GET_INTRO_JSON=${{ secrets.NEXT_PUBLIC_GET_INTRO_JSON }}" >> .env
        echo "NEXT_PUBLIC_SEND_MAIL_URL_PROD=${{ secrets.NEXT_PUBLIC_SEND_MAIL_URL_PROD }}" >> .env
        echo "NEXT_PUBLIC_SEND_MAIL_URL=${{ secrets.NEXT_PUBLIC_SEND_MAIL_URL }}" >> .env
        echo "NEXT_PUBLIC_SEND_ERROR_LOG=${{ secrets.NEXT_PUBLIC_SEND_ERROR_LOG }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_NAME=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_NAME }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_EMAIL=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_EMAIL }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_ERROR_MESSAGE=${{ secrets.NEXT_PUBLIC_CONTACT_ERROR_MESSAGE }}" >> .env
        echo "NEXT_PUBLIC_CONTACT_CONFIRM=${{ secrets.NEXT_PUBLIC_CONTACT_CONFIRM }}" >> .env
        echo "NEXT_PUBLIC_MAIN_TITLE_PREFIX=${{ secrets.NEXT_PUBLIC_MAIN_TITLE_PREFIX }}" >> .env
        echo "NEXT_PUBLIC_NOTICE_SUCCESSED=${{ secrets.NEXT_PUBLIC_NOTICE_SUCCESSED }}" >> .env
        echo "NEXT_PUBLIC_NOTICE_FAILED=${{ secrets.NEXT_PUBLIC_NOTICE_FAILED }}" >> .env
        echo "NEXT_PUBLIC_SKILLS_CARD_FIRST_SHOW_SUM=${{ secrets.NEXT_PUBLIC_SKILLS_CARD_FIRST_SHOW_SUM }}" >> .env
        echo "NEXT_PUBLIC_SKILLS_CARD_LOAD_COUNT=${{ secrets.NEXT_PUBLIC_SKILLS_CARD_LOAD_COUNT }}" >> .env

        # ...他の環境変数を追加...
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

    - name: Logout from Google Container Registry
      run: docker logout gcr.io